name: Publish Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check Out the Repo
      - uses: actions/checkout@v2
    
      - name: Log Into DockerHub
        uses: docker/login-action
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action
        with:
          images: ${{secrets.DOCKER_USER}}/${{github.repository}}
          
      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag markfeit/${{github.repository}}:$(echo $GITHUB_SHA | head -c7)

      - name: Push to DockerHub
        run: docker push ${{secrets.DOCKER_USER}}/docker-template:$(echo $GITHUB_SHA | head -c7)
