name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Log Into Docker
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag markfeit/docker-template:$(date +%s)

    - name: Push to DockerHub
      run: docker push ${{secrets.DOCKER_USER}}/docker-template:$(echo $GITHUB_SHA | head -c7)
