name: Publish Docker Image

# TODO: Figure out how to publish this on multiple architectures.
# One possibility: https://github.com/marketplace/actions/run-on-architecture

on:
  release:
    types: [ published ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Log Into DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          
      - name: Get Release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}    
          
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ steps.buildx.outputs.platforms }}
          push: true
          tags: ${{github.repository}}:${{steps.get_release.outputs.tag_name}},${{github.repository}}:latest
