name: Publish Docker Image

on:
  release:
    types: [ published ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log Into DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          
          
      - name: Extract Tag
        id: tag
        uses: actions/github-script@0.2.0
        with:
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');
          
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{github.repository}}:${{steps.tag.outputs.result}},${{github.repository}}:latest
